export type RegexExpr =
  | { type: 'epsilon' }
  | { type: 'empty' }
  | { type: 'symbol'; value: string }
  | { type: 'state'; name: string }
  | { type: 'concat'; left: RegexExpr; right: RegexExpr }
  | { type: 'union'; left: RegexExpr; right: RegexExpr }
  | { type: 'star'; expr: RegexExpr };

export function isEpsilon(expr: RegexExpr): boolean {
  return expr.type === 'epsilon';
}

export function isEmpty(expr: RegexExpr): boolean {
  return expr.type === 'empty';
}

export function formatExpr(expr: RegexExpr, parentPrec: number = 0): string {
  if (expr.type === 'epsilon') return 'ε';
  if (expr.type === 'empty') return '∅';
  if (expr.type === 'symbol') return expr.value;
  if (expr.type === 'state') return expr.name;
  if (expr.type === 'star') {
    const inner = formatExpr(expr.expr, 3);
    if (expr.expr.type === 'union' || expr.expr.type === 'concat') {
      return `(${inner})*`;
    }
    return `${inner}*`;
  }
  if (expr.type === 'concat') {
    // precedence 2
    const s = `${formatExpr(expr.left, 2)}${formatExpr(expr.right, 2)}`;
    if (parentPrec > 2) return `(${s})`;
    return s;
  }
  if (expr.type === 'union') {
    // precedence 1
    const s = `${formatExpr(expr.left, 1)} + ${formatExpr(expr.right, 1)}`;
    if (parentPrec > 1) return `(${s})`;
    return s;
  }
  return '';
}

export function simplify(expr: RegexExpr): RegexExpr {
  if (expr.type === 'star') {
    const inner = simplify(expr.expr);
    if (inner.type === 'empty' || inner.type === 'epsilon') return { type: 'epsilon' };
    return { type: 'star', expr: inner };
  }
  if (expr.type === 'concat') {
    let left = simplify(expr.left);
    let right = simplify(expr.right);
    if (left.type === 'empty' || right.type === 'empty') return { type: 'empty' };
    if (left.type === 'epsilon') return right;
    if (right.type === 'epsilon') return left;
    return { type: 'concat', left, right };
  }
  if (expr.type === 'union') {
    let left = simplify(expr.left);
    let right = simplify(expr.right);
    if (left.type === 'empty') return right;
    if (right.type === 'empty') return left;
    
    // Simplistic R + R = R check
    if (formatExpr(left) === formatExpr(right)) return left;
    
    return { type: 'union', left, right };
  }
  return expr;
}

export function substitute(expr: RegexExpr, targetState: string, replacement: RegexExpr): RegexExpr {
  if (expr.type === 'state') {
    if (expr.name === targetState) return replacement;
    return expr;
  }
  if (expr.type === 'star') {
    return { type: 'star', expr: substitute(expr.expr, targetState, replacement) };
  }
  if (expr.type === 'concat') {
    return { type: 'concat', left: substitute(expr.left, targetState, replacement), right: substitute(expr.right, targetState, replacement) };
  }
  if (expr.type === 'union') {
    return { type: 'union', left: substitute(expr.left, targetState, replacement), right: substitute(expr.right, targetState, replacement) };
  }
  return expr;
}

// Attempts to extract P and Q from R = Q + R P
// Returns { Q, P } if matches, else null
export function extractArden(expr: RegexExpr, stateName: string): { Q: RegexExpr[], P: RegexExpr[] } | null {
  // We expect expr to be a union of terms.
  const terms: RegexExpr[] = [];
  const gatherTerms = (e: RegexExpr) => {
    if (e.type === 'union') {
      gatherTerms(e.left);
      gatherTerms(e.right);
    } else {
      terms.push(e);
    }
  };
  gatherTerms(expr);

  const Qs: RegexExpr[] = [];
  const Ps: RegexExpr[] = [];

  for (const t of terms) {
    if (t.type === 'concat' && t.left.type === 'state' && t.left.name === stateName) {
      Ps.push(t.right);
    } else if (t.type === 'concat' && t.right.type === 'state' && t.right.name === stateName) {
      // In R = Q + RP, it must be R P. If it's PR, Arden's theorem as typically stated (R = QP*) doesn't strictly apply unless we use R = P*Q for left-linear.
      // Assuming right-linear equations generated by incoming transitions:
      // Equation for q_j: q_j = sum (q_i . a). So we have R = Q_i . a + ...
      // Wait, incoming transitions mean: state = source * symbol
      // So R = Q + P R ? No, R = Q + R P if R is on the left of the concat.
      // Wait, the prompt says: "incoming transitions... A = ε + B·1, B = A·0"
      // If we substitute: B = (ε + B·1)·0 = ε·0 + B·1·0
      // This is B = Q + B·P  (where Q = ε·0, P = 1·0).
      // So R is the left operand of concat.
      // What if it's the right operand? P·B? Incoming transitions from itself would be B = B·1. So left operand is B.
      
      // Let's only handle R as left operand for now to match the prompt's `R = Q + RP` and `B = B·10`
      Ps.push(t.right); // Fallback: if we had a reversed logic, but we won't. Wait, the condition above caught left operand.
      // This else-if is for when R is the right operand. If R is right operand, it's R = Q + PR -> R = P*Q.
      // Prompt uses R = Q + RP -> R = QP*. Let's stick to R as left operand.
    } else {
      Qs.push(t);
    }
  }

  return { Q: Qs, P: Ps };
}

export function buildUnion(terms: RegexExpr[]): RegexExpr {
  if (terms.length === 0) return { type: 'empty' };
  let res = terms[0];
  for (let i = 1; i < terms.length; i++) {
    res = { type: 'union', left: res, right: terms[i] };
  }
  return res;
}

export function applyArden(expr: RegexExpr, stateName: string): RegexExpr | null {
  const extracted = extractArden(expr, stateName);
  if (!extracted) return null;
  if (extracted.P.length === 0) return expr; // No self-reference

  const Q = buildUnion(extracted.Q);
  const P = buildUnion(extracted.P);

  // R = Q P*
  return {
    type: 'concat',
    left: Q,
    right: { type: 'star', expr: P }
  };
}
